version: "2"

volumes:
  postgis-data:
  django-postgis-dbbackup-data:
  sftpbackup-postgis-target-data:
  shared-volume:

services:

  postgis:
    image: kartoza/postgis:11.0-2.5
    ports:
      - "55432:5432"
    environment:
      POSTGRES_USER: ${QGISFEED_DOCKER_DBUSER}
      POSTGRES_PASS: ${QGISFEED_DOCKER_DBPASSWORD}
      POSTGRES_DBNAME: ${QGISFEED_DOCKER_DBNAME}
      ALLOW_IP_RANGE: ${POSTGRES_HBA_RANGE}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    volumes:
      - shared-volume:/var/lib/postgresql
    networks:
      internal:

  dbbackup:
    image: kartoza/pg-backup:11.0
    environment:
      DUMPPREFIX: PG_qgis_feed
      PGHOST: db
      PGPORT: '5432'
      PGDATABASE: ${QGISFEED_DOCKER_DBNAME}
      PGPASSWORD: ${QGISFEED_DOCKER_DBPASSWORD}
      PGUSER: ${QGISFEED_DOCKER_DBUSER}
    volumes:
      - django-postgis-dbbackup-data:/backups
      - sftpbackup-postgis-target-data:/pg_backup
    links:
      - postgis

  sftppgbackup:
    image: kartoza/sftp-backup:1.0
    environment:
      DAILY: '14'
      DUMPPREFIX: PG-qgis-feed
      MONTHLY: '12'
      TARGET_FOLDER: /pg_backup
      USE_SFTP_BACKUP: 'False'
      YEARLY: '3'
    volumes:
      - sftpbackup-postgis-history-data:/backups
      - sftpbackup-postgis-target-data:/pg_backup
    links:
      - postgis

  qgisfeed:
    image: qgis/feed:latest
    environment:
      - QGISFEED_DOCKER_DBNAME
      - QGISFEED_DOCKER_DBUSER
      - QGISFEED_DOCKER_DBPASSWORD
    command: /code/entrypoint_production.sh
    expose:
      - "8000"
    volumes:
      - shared-volume:/shared-volume
    depends_on:
      - postgis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    networks:
      internal:

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - shared-volume:/shared-volume
    links:
      - qgisfeed
    restart: always
    networks:
      internal:

networks:
    internal:
